# ansible/inventory.ini

# Control Plane node
[control_plane]
control-plane ansible_connection=kubectl ansible_kubectl_pod="label:component=control-plane"

# Database group - targets the Pod with the 'role: database' label
[worker_db]
worker-db ansible_connection=kubectl ansible_kubectl_pod="{{ lookup ('pipe', 'kubectl get pod -l role=database -o jsonpath=\"{.items[0].metadata.name}\"') }}"

# App group - targets the Pod with the 'role: app' label
[worker_app]
worker-app ansible_connection=kubectl ansible_kubectl_pod="label:role=app"

# Proxy group - targets the Pod with the 'role: proxy' label
[worker_proxy]
worker-proxy ansible_connection=kubectl ansible_kubectl_pod="label:role=proxy"

# Legacy Node - standalone Docker container accessible via SSH
[legacy]
legacy-node ansible_host=10.10.0.6 ansible_user=root ansible_connection=ssh

# Global variables for all hosts
[all:vars]
ansible_python_interpreter=/usr/bin/python3